teste_frontend:
    resource: "@MastopTesteBundle/Controller/Frontend/TesteController.php"
    type: annotation
    prefix:   /teste
teste_backend:
    resource: "@MastopTesteBundle/Controller/Backend/TesteController.php"
    type: annotation
    prefix:   /admin/teste