_home:
    pattern:  /
    defaults: { _controller: MastopSystemBundle:Frontend\Home:index }
parameters_backend:
    resource: "@MastopSystemBundle/Controller/Backend/ParametersController.php"
    type: annotation
    prefix:   /admin/preferencias